"""
vision_extract.py
-----------------
Two-tier front-of-pack claim extraction pipeline.

Tier 1: Azure AI Vision Read API (OCR)
    Extracts raw text from product front-of-pack images.
    Cost: ~1.50 CHF / 1,000 images.

Tier 2: GPT-4o-mini on extracted text (not images)
    Parses OCR text into structured claim JSON.
    Cost: ~0.50 CHF / 1,000 calls.
    Much cheaper than sending images directly to GPT-4V.

Input:
    data/sample/smart_sample_<timestamp>.csv
    (generated by smart_sample.py)

Output:
    data/sample/vision_results_<timestamp>.csv
    - barcode, product_name, brands, tier
    - ocr_text: raw text from Azure Vision
    - claims_json: structured claims from GPT-4o-mini
    - claims_parsed: flattened claim columns
    - ocr_status, llm_status, error_message

Usage:
    # Test on 10 products first
    python pipeline/vision_extract.py --test

    # Full run
    python pipeline/vision_extract.py

    # Resume interrupted run from a checkpoint
    python pipeline/vision_extract.py --resume

Environment variables required:
    AZURE_VISION_ENDPOINT  e.g. https://your-resource.cognitiveservices.azure.com/
    AZURE_VISION_KEY       32-character key from Azure portal
    AZURE_OPENAI_ENDPOINT  e.g. https://your-resource.openai.azure.com/
    AZURE_OPENAI_KEY       key from Azure OpenAI portal
    AZURE_OPENAI_DEPLOYMENT  e.g. gpt-4o-mini

    OR set them in a .env file in the project root.

Cost controls:
    Set AZURE_COST_ALERT_CHF=80 to stop processing when estimated
    cost exceeds 80 CHF. Hard stop before credits run out.

See docs/ADR.md ADR-010 for architecture rationale.
"""

import os
import sys
import json
import time
import argparse
import requests
import pandas as pd
from datetime import datetime
from pathlib import Path

# ── Load .env if present ──────────────────────────────────────────────────────
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # dotenv optional — can set env vars directly

ROOT       = Path(__file__).parent.parent
SAMPLE_DIR = ROOT / "data" / "sample"

# ── Azure configuration ───────────────────────────────────────────────────────

VISION_ENDPOINT   = os.getenv("AZURE_VISION_ENDPOINT", "").rstrip("/")
VISION_KEY        = os.getenv("AZURE_VISION_KEY", "")
OPENAI_ENDPOINT   = os.getenv("AZURE_OPENAI_ENDPOINT", "").rstrip("/")
OPENAI_KEY        = os.getenv("AZURE_OPENAI_KEY", "")
OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o-mini")
COST_ALERT_CHF    = float(os.getenv("AZURE_COST_ALERT_CHF", "80"))

# Cost per 1000 operations (CHF estimates)
OCR_COST_PER_1K   = 1.50
LLM_COST_PER_1K   = 0.50

# ── GPT-4o-mini system prompt ─────────────────────────────────────────────────

SYSTEM_PROMPT = """You are a food labelling analyst. You receive OCR text extracted 
from a packaged food product's front of pack. Extract ALL health and marketing claims.

Return ONLY valid JSON with this exact structure:
{
  "protein_claim": true/false,
  "protein_amount_g": null or number (grams per 100g or per serving if stated),
  "no_added_sugar": true/false,
  "reduced_sugar": true/false,
  "sugar_reduction_pct": null or number (e.g. 32 for "-32%"),
  "no_palm_oil": true/false,
  "no_artificial": true/false,
  "natural_claim": true/false,
  "fortification_claim": true/false,
  "fortification_nutrients": [] or list of nutrient names (e.g. ["magnesium", "vitamin E"]),
  "fibre_claim": true/false,
  "probiotic_claim": true/false,
  "energy_claim": true/false,
  "vitalite_concept": true/false,
  "sustainability_halo": true/false,
  "sustainability_certs": [] or list (e.g. ["rainforest alliance", "organic"]),
  "reformulation_claim": true/false,
  "comparative_claim": true/false,
  "comparative_reference": null or string (e.g. "average biscuits on the market"),
  "glp1_positioning": true/false,
  "other_claims": [] or list of any other health/wellness claims not captured above,
  "no_claims_detected": true/false,
  "ocr_quality": "good"/"partial"/"poor"
}

Rules:
- Set no_claims_detected=true if you find NO health/wellness claims at all
- Set ocr_quality=poor if the text is mostly garbled or unreadable
- Do NOT infer claims — only extract what is explicitly stated
- Return ONLY the JSON object, no explanation, no markdown fences"""


# ── Azure Vision OCR ──────────────────────────────────────────────────────────

def ocr_image(image_url: str, max_retries: int = 3) -> tuple[str, str]:
    """
    Call Azure AI Vision Read API to extract text from image URL.
    Returns (ocr_text, status) where status is 'success'/'failed'/'invalid_url'.
    """
    if not VISION_ENDPOINT or not VISION_KEY:
        return "", "no_credentials"

    if not image_url or "/invalid/" in image_url:
        return "", "invalid_url"

    url = f"{VISION_ENDPOINT}/vision/v3.2/read/analyze"
    headers = {
        "Ocp-Apim-Subscription-Key": VISION_KEY,
        "Content-Type": "application/json",
    }
    body = {"url": image_url}

    for attempt in range(max_retries):
        try:
            # Submit job
            resp = requests.post(url, headers=headers, json=body, timeout=30)

            if resp.status_code == 202:
                # Poll for result
                result_url = resp.headers.get("Operation-Location")
                if not result_url:
                    return "", "no_operation_url"

                for _ in range(10):
                    time.sleep(2)
                    result = requests.get(
                        result_url,
                        headers={"Ocp-Apim-Subscription-Key": VISION_KEY},
                        timeout=30
                    )
                    result_data = result.json()
                    status = result_data.get("status", "")
                    if status == "succeeded":
                        lines = []
                        for page in result_data.get("analyzeResult", {}).get("readResults", []):
                            for line in page.get("lines", []):
                                lines.append(line.get("text", ""))
                        return "\n".join(lines), "success"
                    elif status == "failed":
                        return "", "ocr_failed"
                return "", "ocr_timeout"

            elif resp.status_code == 429:
                wait = int(resp.headers.get("Retry-After", 60))
                print(f"      Rate limited — waiting {wait}s...")
                time.sleep(wait)
                continue

            elif resp.status_code in (400, 415):
                return "", "invalid_image"

            else:
                return "", f"http_{resp.status_code}"

        except requests.exceptions.Timeout:
            if attempt < max_retries - 1:
                time.sleep(5)
                continue
            return "", "timeout"
        except Exception as e:
            return "", f"error_{str(e)[:30]}"

    return "", "max_retries"


# ── GPT-4o-mini claim extraction ──────────────────────────────────────────────

def extract_claims(ocr_text: str, product_name: str = "") -> tuple[dict, str]:
    """
    Send OCR text to GPT-4o-mini for structured claim extraction.
    Returns (claims_dict, status).
    """
    if not OPENAI_ENDPOINT or not OPENAI_KEY:
        return {}, "no_credentials"

    if not ocr_text or len(ocr_text.strip()) < 10:
        return {"no_claims_detected": True, "ocr_quality": "poor"}, "skipped_empty"

    url = (f"{OPENAI_ENDPOINT}/openai/deployments/{OPENAI_DEPLOYMENT}"
           f"/chat/completions?api-version=2024-02-15-preview")

    headers = {
        "api-key": OPENAI_KEY,
        "Content-Type": "application/json",
    }

    user_message = f"Product: {product_name}\n\nFront-of-pack text:\n{ocr_text[:2000]}"

    body = {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_message},
        ],
        "temperature": 0,
        "max_tokens": 500,
    }

    try:
        resp = requests.post(url, headers=headers, json=body, timeout=30)
        if resp.status_code == 200:
            content = resp.json()["choices"][0]["message"]["content"].strip()
            # Strip markdown fences if present
            if content.startswith("```"):
                content = content.split("```")[1]
                if content.startswith("json"):
                    content = content[4:]
            claims = json.loads(content)
            return claims, "success"
        else:
            return {}, f"http_{resp.status_code}"
    except json.JSONDecodeError:
        return {}, "json_parse_error"
    except Exception as e:
        return {}, f"error_{str(e)[:30]}"


# ── Cost tracker ──────────────────────────────────────────────────────────────

class CostTracker:
    def __init__(self, alert_chf: float):
        self.ocr_calls  = 0
        self.llm_calls  = 0
        self.alert_chf  = alert_chf
        self.aborted    = False

    @property
    def estimated_chf(self):
        return (self.ocr_calls * OCR_COST_PER_1K / 1000 +
                self.llm_calls * LLM_COST_PER_1K / 1000)

    def check_budget(self):
        if self.estimated_chf >= self.alert_chf:
            print(f"\n  COST ALERT: {self.estimated_chf:.2f} CHF >= {self.alert_chf} CHF limit")
            print(f"  Stopping to protect Azure credits.")
            self.aborted = True
            return False
        return True

    def summary(self):
        print(f"\n  Cost summary:")
        print(f"    OCR calls:        {self.ocr_calls:,}")
        print(f"    LLM calls:        {self.llm_calls:,}")
        print(f"    Estimated spend:  {self.estimated_chf:.2f} CHF")
        print(f"    Remaining budget: {100 - self.estimated_chf:.2f} CHF")


# ── Main pipeline ─────────────────────────────────────────────────────────────

def find_latest_sample():
    files = sorted(SAMPLE_DIR.glob("smart_sample_*.csv"), reverse=True)
    if not files:
        raise FileNotFoundError(
            "No smart_sample_*.csv found. Run smart_sample.py first."
        )
    return files[0]


def load_checkpoint(output_path):
    """Load already-processed barcodes from a partial output file."""
    if output_path.exists():
        done = pd.read_csv(output_path, dtype={"barcode": str})
        return set(done["barcode"].tolist())
    return set()


def main():
    parser = argparse.ArgumentParser(description="Azure vision claim extraction")
    parser.add_argument("--test",   action="store_true",
                        help="Test mode: process only 10 products")
    parser.add_argument("--resume", action="store_true",
                        help="Resume from checkpoint file")
    parser.add_argument("--input",  type=str, default=None,
                        help="Path to smart_sample CSV (default: auto-detect latest)")
    args = parser.parse_args()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    print(f"\nFunctional Food Radar - vision_extract.py")
    print(f"Run timestamp: {timestamp}")

    # Validate credentials
    missing = []
    if not VISION_ENDPOINT:  missing.append("AZURE_VISION_ENDPOINT")
    if not VISION_KEY:        missing.append("AZURE_VISION_KEY")
    if not OPENAI_ENDPOINT:   missing.append("AZURE_OPENAI_ENDPOINT")
    if not OPENAI_KEY:        missing.append("AZURE_OPENAI_KEY")
    if missing:
        print(f"\n  ERROR: Missing environment variables:")
        for m in missing:
            print(f"    {m}")
        print(f"\n  Add them to .env or set them in your shell:")
        print(f"    set AZURE_VISION_ENDPOINT=https://your-resource.cognitiveservices.azure.com/")
        print(f"    set AZURE_VISION_KEY=your_key_here")
        print(f"    set AZURE_OPENAI_ENDPOINT=https://your-resource.openai.azure.com/")
        print(f"    set AZURE_OPENAI_KEY=your_key_here")
        sys.exit(1)

    # Load smart sample
    input_path = Path(args.input) if args.input else find_latest_sample()
    print(f"  Input: {input_path.name}")
    df = pd.read_csv(input_path, dtype={"barcode": str})
    print(f"  Products in sample: {len(df):,}")

    # Test mode
    if args.test:
        df = df.head(10)
        print(f"  TEST MODE: processing {len(df)} products only")

    # Checkpoint / resume
    output_path = SAMPLE_DIR / f"vision_results_{timestamp}.csv"
    checkpoint_path = SAMPLE_DIR / "vision_results_checkpoint.csv"

    if args.resume and checkpoint_path.exists():
        done_barcodes = load_checkpoint(checkpoint_path)
        df = df[~df["barcode"].isin(done_barcodes)]
        print(f"  Resuming: {len(done_barcodes):,} already done, {len(df):,} remaining")
        output_path = checkpoint_path

    print(f"  Output: {output_path.name}")
    print(f"  Cost alert at: {COST_ALERT_CHF} CHF\n")

    tracker = CostTracker(COST_ALERT_CHF)
    results = []

    for i, row in enumerate(df.itertuples(), 1):
        if not tracker.check_budget():
            break

        barcode     = str(row.barcode)
        product     = str(getattr(row, "product_name", ""))
        brand       = str(getattr(row, "brands", ""))
        image_url   = str(getattr(row, "image_url", ""))
        tier        = getattr(row, "tier", None)

        print(f"  [{i:>5}/{len(df)}] {brand[:25]:<25} {product[:30]:<30}", end=" ")

        # Tier 1: OCR
        ocr_text, ocr_status = ocr_image(image_url)
        tracker.ocr_calls += 1

        # Tier 2: LLM claim extraction
        claims, llm_status = {}, "skipped"
        if ocr_status == "success" and ocr_text:
            claims, llm_status = extract_claims(ocr_text, product)
            tracker.llm_calls += 1

        print(f"OCR:{ocr_status:<12} LLM:{llm_status:<12} "
              f"cost:{tracker.estimated_chf:.3f} CHF")

        result = {
            "barcode":       barcode,
            "product_name":  product,
            "brands":        brand,
            "tier":          tier,
            "image_url":     image_url,
            "ocr_text":      ocr_text,
            "ocr_status":    ocr_status,
            "llm_status":    llm_status,
            "claims_json":   json.dumps(claims) if claims else "",
        }
        # Flatten key claim fields for easy Power BI access
        if claims:
            for key in [
                "protein_claim", "no_added_sugar", "reduced_sugar",
                "no_palm_oil", "no_artificial", "natural_claim",
                "fortification_claim", "fibre_claim", "probiotic_claim",
                "energy_claim", "vitalite_concept", "sustainability_halo",
                "reformulation_claim", "comparative_claim",
                "glp1_positioning", "no_claims_detected", "ocr_quality",
                "protein_amount_g", "sugar_reduction_pct",
                "comparative_reference",
            ]:
                result[f"v3_{key}"] = claims.get(key)
            result["v3_fortification_nutrients"] = "|".join(
                claims.get("fortification_nutrients", []) or []
            )
            result["v3_sustainability_certs"] = "|".join(
                claims.get("sustainability_certs", []) or []
            )
            result["v3_other_claims"] = "|".join(
                claims.get("other_claims", []) or []
            )

        results.append(result)

        # Save checkpoint every 50 products
        if i % 50 == 0:
            pd.DataFrame(results).to_csv(
                checkpoint_path, index=False, encoding="utf-8-sig"
            )

        # Small delay to be polite to Azure
        time.sleep(0.5)

    # Final save
    results_df = pd.DataFrame(results)
    results_df.to_csv(output_path, index=False, encoding="utf-8-sig")

    print(f"\n  -- Summary --------------------------------------------------")
    print(f"  Products processed: {len(results_df):,}")
    if len(results_df):
        ocr_ok  = (results_df["ocr_status"] == "success").sum()
        llm_ok  = (results_df["llm_status"] == "success").sum()
        print(f"  OCR success:        {ocr_ok:,} ({ocr_ok/len(results_df)*100:.0f}%)")
        print(f"  LLM success:        {llm_ok:,} ({llm_ok/len(results_df)*100:.0f}%)")

        if "v3_no_claims_detected" in results_df.columns:
            no_claims = results_df["v3_no_claims_detected"].sum()
            has_claims = llm_ok - no_claims
            print(f"  Products with claims: {has_claims:,}")
            print(f"  Products no claims:   {int(no_claims):,}")

    tracker.summary()
    if tracker.aborted:
        print(f"\n  Run was stopped by cost alert.")
        print(f"  Resume with: python pipeline/vision_extract.py --resume")

    print(f"\n  Saved -> {output_path.name}")
    print(f"  Next step: python pipeline/merge_scores.py\n")


if __name__ == "__main__":
    main()